-- ============================================================================
-- Module: user
-- Identity, authorisation, addresses, sessions.
--
-- Conventions used across every module in this schema:
--   * uuid primary keys, generated by the database (gen_random_uuid, core PG13+)
--   * timestamptz everywhere — never naive timestamps
--   * money as numeric(19,4) + ISO-4217 char(3); never floating point
--   * enums as varchar + CHECK, not native PG enum types (alterable, and maps
--     cleanly to JPA @Enumerated(EnumType.STRING))
--   * every mutating table records WHO acted via (actor_type, actor_user_id) so
--     an agent-driven change is always distinguishable from a human one
-- ============================================================================

-- Shared trigger used by every table carrying updated_at.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

-- ------------------------------------------- roles & permissions -----
CREATE TABLE roles (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name        varchar(64) NOT NULL UNIQUE,
    description text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);


CREATE TRIGGER trg_roles_updated_at
    BEFORE UPDATE ON roles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE permissions (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name        varchar(128) NOT NULL UNIQUE,
    description text,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);


CREATE TRIGGER trg_permissions_updated_at
    BEFORE UPDATE ON permissions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE role_permissions (
    role_id       uuid NOT NULL REFERENCES roles(id)       ON DELETE CASCADE,
    permission_id uuid NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- Seeded before `users`, which now carries a NOT NULL role_id.
--
-- Staff roles, in the order an order passes through them: a MODERATOR assigns
-- the work, a PICKER walks the shelves, a DRIVER carries it out. Nothing
-- advances a PAID order on its own — every step after payment is a person.
INSERT INTO roles (name, description) VALUES
    ('ADMIN',     'Full administrative access'),
    ('MODERATOR', 'Assigns orders to pickers and drivers; confirms the picked order'),
    ('PICKER',    'Picks the lines of an assigned order from the store shelves'),
    ('DRIVER',    'Carries a confirmed order from the store to the customer'),
    ('CUSTOMER',  'Standard shopper');

-- ---------------------------------------------------------------- users -----
CREATE TABLE users (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email          text Unique NOT NULL,
    username       text Unique NOT NULL,
    fname          text        NOT NULL,
    lname          text        NOT NULL,

    -- null for accounts created purely through an OAuth provider
    password_hash  text,
    
    
    -- Values are the JPA enum constant names, so @Enumerated(EnumType.STRING)
    -- round-trips without a converter. Nullable: NULL passes a CHECK.
    gender         varchar(32)
        CHECK (gender IN ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY')),
    date_of_birth  date,
    profile_pic_url text,

    locale         varchar(16) NOT NULL DEFAULT 'en',
    time_zone      varchar(64) NOT NULL DEFAULT 'UTC',

    -- Exactly one role per user. RESTRICT: a role still in use cannot be
    -- deleted out from under its members.
    role_id        uuid        NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,

    is_verified    boolean     NOT NULL DEFAULT false,
    is_active      boolean     NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    deleted_at     timestamptz
);

-- Case-insensitive uniqueness without depending on the citext extension.
CREATE INDEX ix_users_role ON users (role_id);
CREATE UNIQUE INDEX ux_users_email    ON users (lower(email));
CREATE UNIQUE INDEX ux_users_username ON users (lower(username));

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();






-- ------------------------------------------------------ customer profiles ---
-- Per-user preference flags, kept out of `users` so the row every
-- authentication path reads stays narrow. Adding a preference here needs no
-- migration of the table the sign-in query touches.
CREATE TABLE customer_profiles (
    id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,

    -- privacy
    is_activity_tracked  boolean NOT NULL DEFAULT false,
    is_data_shared       boolean NOT NULL DEFAULT false,

    -- notifications
    is_email_notified    boolean NOT NULL DEFAULT true,
    is_security_notified boolean NOT NULL DEFAULT true,
    is_update_notified   boolean NOT NULL DEFAULT true,

    -- May the chat assistant act on this account's behalf? Moved off `users`:
    -- it is a preference, and it belongs with the other preferences.
    agent_enabled        boolean NOT NULL DEFAULT true,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_customer_profiles_user ON customer_profiles (user_id);

CREATE TRIGGER trg_customer_profiles_updated_at
    BEFORE UPDATE ON customer_profiles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------- oauth accounts -----
-- One row per external identity linked to an account. Kept out of `users` so a
-- person can link several providers, and so provider credentials never widen
-- the row every authentication path has to read.
CREATE TABLE oauth_accounts (
    id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id  uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    provider varchar(32) NOT NULL
        CHECK (provider IN ('GOOGLE', 'FACEBOOK', 'APPLE', 'GITHUB')),

    -- The provider's own immutable id for this person: Google's `sub` claim.
    -- Matched on instead of email, because an email can be reassigned.
    provider_user_id text NOT NULL,

    -- Snapshot of what the provider asserted at link time.
    email          text,
    email_verified boolean     NOT NULL DEFAULT false,
    display_name   text,
    avatar_url     text,

    -- Provider credentials, present only when we hold them on the user's
    -- behalf (calendar, contacts). Null for plain sign-in, which needs nothing
    -- after the ID token is verified.
    access_token   text,
    refresh_token  text,
    token_expires_at timestamptz,
    scopes         text,

    linked_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),

    -- An external identity belongs to exactly one local account.
    UNIQUE (provider, provider_user_id),
    -- ...and an account links a given provider at most once.
    UNIQUE (user_id, provider)
);

CREATE INDEX ix_oauth_accounts_user ON oauth_accounts (user_id);

CREATE TRIGGER trg_oauth_accounts_updated_at
    BEFORE UPDATE ON oauth_accounts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- addresses -----
CREATE TABLE addresses (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    
    user_id        uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    label          varchar(64),
    
    recipient_name text        NOT NULL,
    line1          text        NOT NULL,
    line2          text,
    city           text        NOT NULL,
    region         text,
    postal_code    varchar(32),

    country_code   char(2)     NOT NULL,
    phone          text,

    -- One default per user, and it is where their orders go. There is no
    -- billing counterpart: a billing address belongs to the card and is held by
    -- the payment provider, so a copy here would be a second, staler version of
    -- something this database does not own.
    is_default boolean NOT NULL DEFAULT false,

    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    deleted_at     timestamptz
);

CREATE INDEX ix_addresses_user ON addresses (user_id) WHERE deleted_at IS NULL;

-- At most one default per user.
CREATE UNIQUE INDEX ux_addresses_default
    ON addresses (user_id) WHERE is_default AND deleted_at IS NULL;

CREATE TRIGGER trg_addresses_updated_at
    BEFORE UPDATE ON addresses
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------- sessions -----
CREATE TABLE sessions (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- opaque value placed in the `session` cookie by the backend
    
    token        text        NOT NULL UNIQUE,
    device_type  varchar(32),
    user_agent   text,
    ip_address   inet,
    location     text,
    
    -- The session's handle, raw. Never leaves the server: what the client
    -- receives is this value salted and hashed, which is also what appears in
    -- the caller's URLs.
    public_user_id      text NOT NULL,

    -- Per-session salt for that hash. Two sessions with identical handles
    -- would still derive different client-facing values.
    public_user_id_salt text NOT NULL,

    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    revoked_at   timestamptz,
    updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_sessions_public_user_id ON sessions (public_user_id);


CREATE TRIGGER trg_sessions_updated_at
    BEFORE UPDATE ON sessions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX ix_sessions_user    ON sessions (user_id);
CREATE INDEX ix_sessions_expires ON sessions (expires_at) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------- tokens ----
CREATE TABLE tokens (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token      text        NOT NULL UNIQUE,
    token_type varchar(32) NOT NULL
        CHECK (token_type IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET')),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_tokens_user ON tokens (user_id, token_type);

-- ------------------------------------------------------------- seed data ----

CREATE TRIGGER trg_tokens_updated_at
    BEFORE UPDATE ON tokens
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
